## One Dimension Array

In [3]:
import numpy as np

In [2]:
nums_array = np.array([1,2,3,4])
nums_array

array([1, 2, 3, 4])

In [3]:
type(nums_array)

numpy.ndarray

In [5]:
nums_array[-1]

4

In [6]:
nums_array.shape # кортеж с размерностью массива

(4,)

In [7]:
nums_array.ndim # размерность массива

1

In [8]:
nums_array.size # колличество елементов

4

In [9]:
str_array = np.array([True,2,'abc',4.4]) # приводит к одному типу
str_array

array(['True', '2', 'abc', '4.4'], dtype='<U32')

In [11]:
obj_array = np.array([{'city':'London'},{'city':'Berlin'}]) # приводит к одному типу
obj_array

array([{'city': 'London'}, {'city': 'Berlin'}], dtype=object)

## Two Dimension Array

In [30]:
first = np.array([[1,2,3], [3,4,5]])
first

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
first.shape

(2, 3)

In [19]:
first.ndim

2

In [20]:
second = np.array([[7,2,3], [9,4,5]])
second

array([[7, 2, 3],
       [9, 4, 5]])

In [21]:
first + second

array([[ 8,  4,  6],
       [12,  8, 10]])

In [31]:
#создается массив с аналогичным размером и одиничными елементами

first = first + 1
first

array([[2, 3, 4],
       [4, 5, 6]])

In [32]:
np.sum(first)

24

In [33]:
np.sum(first, axis=0) # суммирование по вертикале 

array([ 6,  8, 10])

In [34]:
np.sum(first, axis=1) # суммирование по горизонтале

array([ 9, 15])

In [35]:
np.mean(first, axis=0)

array([3., 4., 5.])

In [38]:
np.max(first, axis=1)

array([4, 6])

## Three Dimension Array

In [44]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [47]:
# shape will be (3,2,4)

np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))),3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [48]:
stock_prices.shape

(3, 2, 4)

In [53]:
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}")
    for index_axis_1, day in enumerate(days):
        print(f"Day: {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0,index_axis_1,index_axis_2]}")
        print("")
    print("")

Stock prices for the Google
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692




## Array Axis

In [23]:
first[1,1]

4

In [25]:
np.concatenate((first,second)) # кортеж массивов, по умолчанию слияние масссивов происходит по оси 0

array([[1, 2, 3],
       [3, 4, 5],
       [7, 2, 3],
       [9, 4, 5]])

In [26]:
np.concatenate((first,second), axis=1)

array([[1, 2, 3, 7, 2, 3],
       [3, 4, 5, 9, 4, 5]])

In [29]:
np.concatenate((np.array([1,2,3]),np.array([4,5,6])))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.concatenate((np.array([1,2,3]),np.array([4,5,6])), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [33]:
np.zeros((3,4)) #заполнение массива нулями

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Random

In [35]:
np.zeros((3,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
np.ones((5,3)) #заполнение массива единицами

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
import random

In [39]:
np.random.random((2,4)) # случайные значение от [0,1]

array([[0.39583837, 0.43424001, 0.46924315, 0.66683797],
       [0.38681434, 0.98202085, 0.06270671, 0.15806536]])

In [ ]:
np.random.seed(0) # обьязательно задавать в той же ячейке
np.random.random((2,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [43]:
np.random.randint(10,20,size=(2,4)) # случайные целые числа с диапазона

array([[18, 11, 16, 17],
       [17, 18, 11, 15]])

In [44]:
# uniform distribution — вероятность генерации любого числа в этом диапазоне — одинакова 

np.random.uniform(10,20,size=(2,4)) # случайные числа с диапазона

array([[18.36078764, 13.3739616 , 16.48171872, 13.6824154 ],
       [19.57155159, 11.4035078 , 18.70087258, 14.73608045]])

In [47]:
# выбор случайного елемента с массива

np.random.choice(np.array([1,'b',3]),size=(2,4))

array([['1', 'b', 'b', '3'],
       ['1', '1', 'b', '1']], dtype='<U21')

## Arange

In [48]:
# возращает новый массив с одинаково распределенными значениями по определеному интервалуъ
# шаг по умолчанию 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(15,25,3) #start,stop,step

array([15, 18, 21, 24])

## Reshape

In [53]:
# модифицирует одномерный массив в двумерный
# меняет размерность массива

np.arange(20).reshape((2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [54]:
np.random.random((10,))

array([0.6818203 , 0.3595079 , 0.43703195, 0.6976312 , 0.06022547,
       0.66676672, 0.67063787, 0.21038256, 0.1289263 , 0.31542835])

In [55]:
np.random.random((10,)).reshape((2,5))

array([[0.36371077, 0.57019677, 0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077]])

## Flatten

In [56]:
# трансформация массива любой размерности в одномерный

np.random.randint(50,80,(4,4,3))

array([[[53, 76, 73],
        [65, 63, 71],
        [71, 66, 67],
        [55, 59, 53]],

       [[50, 55, 50],
        [67, 68, 54],
        [52, 66, 79],
        [53, 52, 60]],

       [[63, 66, 57],
        [71, 59, 50],
        [60, 68, 61],
        [76, 73, 77]],

       [[52, 75, 52],
        [53, 77, 53],
        [68, 64, 53],
        [70, 67, 68]]])

In [57]:
np.random.randint(50,80,(4,4,3)).flatten()

array([77, 64, 59, 76, 51, 54, 60, 72, 61, 58, 61, 52, 69, 66, 50, 72, 50,
       56, 69, 64, 60, 69, 74, 78, 58, 63, 74, 79, 52, 53, 52, 61, 63, 66,
       58, 58, 69, 58, 76, 52, 74, 70, 53, 62, 79, 64, 50, 54])

## Split

In [5]:
# split разбывает массив на несколько подмассивов
np.split(np.random.random((9,)), 4)

ValueError: array split does not result in an equal division

In [7]:
batches = np.split(np.random.random((8,)), 4)

In [13]:
# enumerate возращает последовательность кортежей

for i, batch in enumerate(batches):
    print("batch number:", i)
    print("first element:", batch[0])
    print("second element:", batch[1])
    print("")

batch number: 0
first element: 0.271692244624942
second element: 0.2771051036160369

batch number: 1
first element: 0.08678046916745563
second element: 0.09808444802145455

batch number: 2
first element: 0.8452039048308361
second element: 0.38297135916856095

batch number: 3
first element: 0.5261106059547831
second element: 0.847226779428755



In [14]:
new_arr = np.random.random((10,))
new_arr

array([0.88576125, 0.46237999, 0.24535398, 0.34687199, 0.64178531,
       0.39935316, 0.57331851, 0.52071374, 0.99188536, 0.28837011])

In [16]:
new_arr[new_arr > 0.5]

array([0.88576125, 0.64178531, 0.57331851, 0.52071374, 0.99188536])